//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CISFacultyWeb {
    
    
    public partial class Default {
        
        protected System.Web.UI.HtmlControls.HtmlForm form1;
        
        protected System.Web.UI.WebControls.Button scrapeBtn;
        
        protected System.Web.UI.WebControls.TextBox resultTextBox;
        
        protected System.Web.UI.WebControls.DropDownList facultyListCombo;
        
        protected System.Web.UI.WebControls.DropDownList htmlScheduleCombo;
        
        protected System.Web.UI.WebControls.DropDownList classCombo;
        
        protected System.Web.UI.WebControls.Button findOut1Btn;
        
        protected System.Web.UI.WebControls.DropDownList classCombo3;
        
        protected System.Web.UI.WebControls.Button findOut2Btn;
        
        protected System.Web.UI.WebControls.DropDownList timeCombo;
        
        protected System.Web.UI.WebControls.Button findOut3Btn;
        
        protected System.Web.UI.WebControls.Button findOut4Btn;
        
        protected System.Web.UI.WebControls.DropDownList bigFacList;
        
        protected System.Web.UI.WebControls.Button addBtn;
        
        protected System.Web.UI.WebControls.Button removeBtn;
        
        protected System.Web.UI.WebControls.Button findOut5Btn;
        
        protected System.Web.UI.WebControls.TextBox listOfChosenText;
    }
}
